GET http://localhost:3003/character?name=daniel

###

PUT  http://localhost:3003/character
Content-Type: application/json

{
    "name":"Daniel",
    "gender":"MALE",
    "description":"Estudante"
}

###

###
DELETE http://localhost:3003/character/1